# Generated by Django 5.0.14 on 2026-06-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='criado_por',
        ),
        migrations.AddField(
            model_name='evento',
            name='organizador',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Inscricao',
        ),
    ]
