# Generated by Django 5.0.14 on 2026-06-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_evento_criado_por_evento_organizador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bug', 'Bug / Erro'), ('melhoria', 'Melhoria / Nova funcionalidade'), ('duvida', 'Dúvida / Suporte')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('email_contato', models.EmailField(blank=True, max_length=254)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_analise', 'Em Análise'), ('em_desenvolvimento', 'Em Desenvolvimento'), ('resolvida', 'Resolvida'), ('fechada', 'Fechada')], default='aberta', max_length=20)),
                ('protocolo', models.CharField(max_length=20, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitação de Manutenção',
                'verbose_name_plural': 'Solicitações de Manutenção',
                'ordering': ['-criado_em'],
            },
        ),
    ]
