# Generated by Django 5.0.14 on 2026-06-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_solicitacaomanutencao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocoloCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('contador', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contador de Protocolo',
                'verbose_name_plural': 'Contadores de Protocolo',
            },
        ),
    ]
